### ISSUE TITLE
Fix code scanning alert - SAST

### ISSUE THREAD

**Issue by hywenklis** [hywenklis/buddy-api#73]
Tracking issue for:
- [x] https://github.com/hywenklis/buddy-api/security/code-scanning/6

**Comment by hywenklis** [comment]
### Resolução do Alerta de Segurança: Execução do CodeQL

Olá a todos,

Recebemos um alerta indicando que a análise do CodeQL não está sendo executada em todos os commits. Para resolver isso, tomaremos as seguintes medidas:

#### **Ações a Serem Tomadas**

1. **Verificação e Atualização da Configuração do Cron**:
   - A configuração do cron está programada para rodar semanalmente às segundas-feiras. Vamos confirmar se a execução está ocorrendo conforme o esperado e considerar ajustes se necessário.

2. **Atualização do Workflow para Todos os Branches**:
   - Ajustaremos a configuração do workflow para garantir que a análise seja executada não apenas no branch `main`, mas também em outros branches, como `develop` e `feature/**`.

3. **Revisão dos Logs de Execução**:
   - Verificaremos os logs das execuções do workflow para identificar possíveis falhas e garantir que o CodeQL esteja sendo executado conforme o esperado.

4. **Adição de Notificações**:
   - Implementaremos notificações para alertar sobre falhas na execução da análise CodeQL.

#### **Configuração Atualizada**

Aqui está a configuração revisada do arquivo `.github/workflows/codeql.yml`:

```yaml
name: "CodeQL"

on:
  push:
    branches: ["main", "develop", "feature/**"]
  pull_request:
    branches: ["main", "develop", "feature/**"]
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: read
  security-events: write

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ["java"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
```

## Próximos Passos
Estamos implementando essas alterações para garantir que a análise do CodeQL seja realizada de forma abrangente em todos os commits e pull requests. Agradecemos qualquer feedback ou sugestões adicionais.

Obrigado pela colaboração e pelo empenho em manter o nosso projeto seguro!
